### ISSUE TITLE
Behaviour of marker inconsistent between design document and code

### ISSUE THREAD

**Issue by nkashy1** [doc-ai/tensorio-models#21]
Behaviour of marker inconsistent between design document and code.

Design doc link: https://docs.google.com/document/d/1ssAMcan5cFaX8I29fzijE26TiWXlRYilHKrMhfAnaXo/edit?usp=sharing

Running `git grep "TODO(frederick)"` will give you a the instances of this in the test code.

No need to change the code, but this should be reflected in the design doc.

**Comment by fkautz** [comment]
This will be fixed by #46
