### ISSUE TITLE
Update operations have unspecified behaviour on id updates

### ISSUE THREAD

**Issue by nkashy1** [doc-ai/tensorio-models#23]
Update validation -- e.g. UpdateModel does not error out if caller tries to update ModelId; it simply ignores the ModelId field.

It would be preferable to error out.

**Comment by fkautz** [comment]
There are two possibilities here:

- model.modelid is empty, we should ignore this.
- model.modelid is not empty and does not match request.modelid. We should fail here.

**Comment by fkautz** [comment]
This should be resolved in #47
