### ISSUE TITLE
Guarantee info dictionary in GET ~/checkpoints/checkpointId> only has string values

### ISSUE THREAD

**Issue by phildow** [doc-ai/tensorio-models#38]
GET a specific checkpoint returns an info property in its response:

```
"info": {
  "standard-1-accuracy": "0.934"
}
```

The design document doesn't make it explicit but if this information is descriptive only can we guarantee a mapping from string -> string objects in it?

**Comment by fkautz** [comment]
The API server guarantees it will be a string. I've updated the document.
