### ISSUE TITLE
createdAt on checkpoints should report time to milliseconds level of granularity

### ISSUE THREAD

**Issue by nkashy1** [doc-ai/tensorio-models#82]
@phildow : Can you post a format string for the time?

**Comment by phildow** [comment]
`yyyy-MM-dd'T'HH:mm:ss.SSSZ`

**Comment by phildow** [comment]
Date strings with this format look like:

```
2019-04-20T16:20:00.000+0000
```

**Comment by nkashy1** [comment]
Currently, the `GetCheckpointResponse` represent the time as a `google.protobuf.Timestamp`, on which the granularity cannot be configured:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto

I think we are better off handling correctly on client side and not making a server change.

@phildow, @tpdocai : What do you think?

**Comment by nkashy1** [comment]
After discussion with @phildow , we have discussed that lowering of temporal resolution can be handled on the client side. The current response has nanosecond resolution, so does not need addressing on the server side.
